name: ci node workflow
on:
  push:
    branches:
      - main

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name:
        uses: actions/setup-node@v4
      - name: installatie dependencies
        run: npm ci
      - name: uivoering van unit tests
        run: npm test
      - name: genreatie van een test coverage rapport
        run: npm test --coverage
      - name: listing contents
        run: ls -alhR
      - name: make artifact
        uses: actions/upload-artifact@v4
        with:
          name: coveragerapport
          path: coverage/
